/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#282b27",
        "on-secondary": "#28332f",
        "secondary": "#bec9c4",
        "error-container": "#93000a",
        "midnight-base": "#0D1311",
        "surface-container-low": "#1a1c19",
        "outline": "#8c9389",
        "on-error-container": "#ffdad6",
        "surface-dim": "#121411",
        "surface": "#121411",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "background": "#121411",
        "on-surface-variant": "#c2c8be",
        "primary-fixed-dim": "#a7d1a6",
        "surface-container-highest": "#333532",
        "primary": "#a7d1a6",
        "on-secondary-fixed": "#141e1b",
        "inverse-on-surface": "#2f312e",
        "forest-accent": "#2D4436",
        "tertiary-container": "#677451",
        "on-tertiary": "#293417",
        "on-tertiary-fixed-variant": "#3f4b2c",
        "on-primary": "#133819",
        "on-tertiary-fixed": "#141f05",
        "secondary-container": "#3e4945",
        "secondary-fixed": "#dae5e0",
        "inverse-surface": "#e2e3de",
        "secondary-fixed-dim": "#bec9c4",
        "tertiary-fixed": "#dae8be",
        "surface-bright": "#383a36",
        "on-surface": "#e2e3de",
        "surface-container-lowest": "#0d0f0c",
        "primary-fixed": "#c3eec0",
        "primary-container": "#527853",
        "sage-highlight": "#B7C0A8",
        "on-secondary-fixed-variant": "#3e4945",
        "on-primary-fixed-variant": "#2a4f2e",
        "surface-tint": "#a7d1a6",
        "on-background": "#e2e3de",
        "outline-variant": "#424941",
        "on-primary-fixed": "#002107",
        "on-primary-container": "#d3ffd0",
        "on-tertiary-container": "#ebface",
        "surface-variant": "#333532",
        "surface-container": "#1e201d",
        "inverse-primary": "#426743",
        "tertiary": "#becca3",
        "tertiary-fixed-dim": "#becca3",
        "on-secondary-container": "#acb8b3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "base": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Noto Sans KR"],
        "headline-lg": ["Noto Sans KR"],
        "headline-md": ["Noto Sans KR"],
        "caption": ["Noto Sans KR"],
        "body-lg": ["Noto Sans KR"],
        "display-lg": ["Noto Sans KR"],
        "label-sm": ["Noto Sans KR"],
        "headline-lg-mobile": ["Noto Sans KR"],
        "body-md": ["Noto Sans KR"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "100" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "300" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
